config/routes.rb
Rails.application.routes.draw do
  get 'ask', to: 'question#ask', as: 'ask'
  get 'answer', to: 'question#answer', as: 'answer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController

  def ask

  end

  def answer
    @answer = params[:question]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/question/answer.html.erb
<h1>Question#answer</h1>
<p>Find me in app/views/question/answer.html.erb</p>

<% if @answer == "I am going to work" %>
  Great!
<% elsif @answer.include? "?" %>
  Silly question, get dressed and go to work!
<% else %>
  I don't care, get dressed and go to work!
<% end %>

<%= link_to "ask", ask_path %>

app/views/question/ask.html.erb
<h1>Question#ask</h1>
<p>Find me in app/views/question/ask.html.erb</p>

<form action="answer">
  <input type="text" name="question">
  <input type="submit" value="Ask!">
</form>